### ISSUE TITLE
celshader and shadows

### ISSUE THREAD

**Issue by onelsonic** [armory3d/driver_celshade#1]
Hi, I have been playing around trying to create a custom RenderPath,
and I would like to have shadows as well.
I noticed that the shadows in the celshade renderpath are not working/activated.
(same when you try the example : https://github.com/armory3d/driver_celshade_example)
I have the following console error when trying it to use it : 

	Warning : Uniform sunCol not found

How can we add shadows rendered in a custom RenderPath ?

Thank you

**Comment by luboslenco** [comment]
Yo, I have fixed the shadows at https://github.com/armory3d/driver_celshade/commit/d017d9add3fb5eac6ed999845ca0b15871166f9f (although only sun light is implemented). Hope that helps!

**Comment by onelsonic** [comment]
Great! I see now how the shadows works - I will try to enable it only on certain mesh.
Thank you
