### ISSUE TITLE
displacement / normal map never work in the Celshader render

### ISSUE THREAD

**Issue by onelsonic** [armory3d/driver_celshade#12]
"displacement" in the celshade render never been effective since I think this Celshade render flattens all materials out.
I think this should be corrected as normally maps/displacement should work in the celshade/Toon renderer.

Please find my test file here : 
https://github.com/onelsonic/armory_tests/raw/master/celshadedisplacement.7z
Celshade :
<img width="600" alt="2021-05-29 17_46_04-test" src="https://user-images.githubusercontent.com/53947594/120076546-6403b200-c0a6-11eb-850c-06a7699cb8df.png">
Desktop:
<img width="600" alt="2021-05-29 17_53_17-displacement" src="https://user-images.githubusercontent.com/53947594/120076626-c957a300-c0a6-11eb-9c48-fbea81b60ddd.png">

**Comment by MoritzBrueckner** [comment]
I don't know why this is, but for some reason the displacement value is multiplied by 0.1 in the vertex shader generated with the celshade renderpath:

https://github.com/armory3d/driver_celshade/blob/9cf36c116f3c5d7ed1b61d2dbcc59e203607d701/blender.py#L108

After removing that multiplication everything looks as expected but I don't know which way around is the correct one – Cycles and Eevee both seem to just "fake" displacement without actually moving the vertices. But a factor of 0.1 is something in between no/fake and clearly visible displacement, so in my opinion we should get rid of it, I don't know.

**Comment by onelsonic** [comment]
I did many tests and yes that was what caused the displacement mapping to not work in the Celshade renderer.
By removing the *0.1 multiplication factor it corrected the displacement mapping. 👍 
<img width="600" alt="2021-06-01 14_00_34-celshadedisplacement" src="https://user-images.githubusercontent.com/53947594/120319892-c72d5880-c2e1-11eb-9ef8-8c863b95f81a.png">
