### ISSUE TITLE
BUG : "cast shadow/Receive shadow" not working - celshade driver pass shadows been applied to all 3Dmodels in the scene unconditionally

### ISSUE THREAD

**Issue by onelsonic** [armory3d/driver_celshade#2]
Hi,
I looked at the code, but cannot figure how to enable the "cast shadow/Receive shadow" feature with the celshade or any custom RenderPath.
The shadow will cast everwhere.
How can we make it work properly so it respects the "Receive shadow" status from the materials?

**Comment by luboslenco** [comment]
Implemented receive shadow prop at https://github.com/armory3d/driver_celshade/commit/b01e0fbb00a8c9a175b07d6b2152ddb6a240e34d, thanks for report!
